from .llm import ContentGenerator
from typing import Optional, AsyncGenerator
from pydantic import BaseModel, Field
from config.models import Model
from asyncio import Queue, Lock
from .models import create_thread, create_content


class ThreadGenerate(BaseModel):
    thread_id: int = Field(description="The id of the thread")
    model: str = Field(
        description="The model to use for the thread", default=Model.GPT_4O_MINI.value)
    extra_instructions: Optional[str] = Field(
        description="Extra instructions for the thread")


class Content(BaseModel):
    thread_topic: str = Field(description="The topic of the thread")
    content: str = Field(description="The content of the thread")
    current_idx: int = Field(description="The current index of the content")
    content_id: int = Field(description="The id of the content")


class ThreadGenerateResponse(BaseModel):
    thread_id: int = Field(description="The id of the thread")
    content: Content = Field(description="The content of the thread")


class Thread:
    def __init__(self, topic: str, id: int) -> None:
        self.id = id
        self.topic = topic
        self.content_generator = ContentGenerator(topic)
        self.current_idx = 0
        self.is_generating = False
        self.generation_lock = Lock()
        self.content_queue = Queue()

    async def __create_content_model(self, thread_topic: str, content: str) -> int:
        """
        Create a new ThreadContent instance in the DB asynchronously.
        """
        return await create_content(self.id, content, thread_topic)

    async def generate_content(
        self,
        model: str = Model.GPT_4O_MINI.value,
        extra_instructions: Optional[str] = None
    ) -> AsyncGenerator[Content, None]:
        """
        Generate content asynchronously via the content generator.
        """
        async with self.generation_lock:
            if self.is_generating:
                while True:
                    try:
                        content = await self.content_queue.get()
                        yield content
                    except Exception:
                        break
            else:
                self.is_generating = True
                try:
                    async for data in self.content_generator.generate_content_stream(self.current_idx, model):
                        self.current_idx += 1
                        topic = data.topic
                        content = data.topic_content
                        content_id = await self.__create_content_model(topic, content)

                        content = Content(
                            thread_topic=topic,
                            content=content,
                            current_idx=self.current_idx,
                            content_id=content_id
                        )

                        await self.content_queue.put(content)
                        yield content
                finally:

                    self.is_generating = False
                    while not self.content_queue.empty():
                        self.content_queue.get_nowait()


class ThreadService:
    """
    Service class for managing thread operations, including creation and content generation.
    """

    def __init__(self):
        """
        Initialize the ThreadService with an empty threads dictionary.

        The dictionary maps thread IDs to their corresponding Thread instances.
        """
        self.threads: dict[int, Thread] = {}

    async def __create_thread(self, topic: str) -> int:
        """
        Create a new thread entry in the database asynchronously.

        Args:
            topic (str): The topic or title for the new thread.

        Returns:
            int: The unique identifier of the created thread.
        """
        thread_id = await create_thread(topic)
        self.threads[thread_id] = Thread(topic, thread_id)
        return thread_id

    async def generate_content(self, thread_generate: ThreadGenerate) -> AsyncGenerator[ThreadGenerateResponse, None]:
        """
        Generate content for a specific thread asynchronously based on given generation parameters.

        This method retrieves the thread using the provided thread ID and then yields content chunks
        as they are generated by the thread's content generator.

        Args:
            thread_generate (ThreadGenerate): An object containing the following attributes:
                - thread_id (int): The ID of the thread for which to generate content.
                - model (str): The model identifier to be used for content generation.
                - extra_instructions (Optional[str]): Additional instructions to guide the content generation.

        Yields:
            ThreadGenerateResponse: A response object containing the thread ID and a generated content chunk.

        Raises:
            ValueError: If the thread associated with the provided thread ID does not exist.
        """
        thread_id = thread_generate.thread_id
        model = thread_generate.model
        extra_instructions = thread_generate.extra_instructions

        if thread_id not in self.threads:
            raise ValueError("Thread not found")

        content_generator = self.threads[thread_id]
        async for content in content_generator.generate_content(model, extra_instructions):
            yield ThreadGenerateResponse(
                thread_id=thread_id,
                content=content,
            )

    async def create_thread(
        self,
        topic: str,
        model: str = Model.GPT_4O_MINI.value,
        extra_instructions: Optional[str] = None
    ) -> AsyncGenerator[ThreadGenerateResponse, None]:
        """
        Create a new thread in the database and initiate its content generation process asynchronously.

        This method creates a new thread record and then immediately starts generating its content
        using the specified model and any extra instructions provided.

        Args:
            topic (str): The topic or title for the new thread.
            model (str, optional): The model identifier for content generation. Defaults to Model.GPT_4O_MINI.value.
            extra_instructions (Optional[str], optional): Additional instructions for content generation. Defaults to None.

        Yields:
            ThreadGenerateResponse: A response object containing the thread ID and a generated content chunk.
        """
        thread_id = await self.__create_thread(topic)
        thread_generate = ThreadGenerate(
            thread_id=thread_id,
            model=model,
            extra_instructions=extra_instructions
        )
        async for content in self.generate_content(thread_generate):
            yield content
